baseURL = "https://secrium.io/"
languageCode = "en-us"
title = "Secrium"
author = "Yahya Kharraz"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "Secrium"
description = "Security Professionals Companion"
bgimg = "/img/background.png"